"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .gradeelementary import GradeElementary, GradeElementaryTypedDict
from .gradeelementaryupdate import GradeElementaryUpdate, GradeElementaryUpdateTypedDict
from meitner.types import BaseModel
from meitner.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class GradeElementaryUpdateRequestTypedDict(TypedDict):
    id: str
    r"""The unique identifier of the GradeElementary to update"""
    grade_elementary_update: GradeElementaryUpdateTypedDict
    r"""Request body"""


class GradeElementaryUpdateRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The unique identifier of the GradeElementary to update"""

    grade_elementary_update: Annotated[
        GradeElementaryUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Request body"""


class GradeElementaryUpdateResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: GradeElementaryTypedDict


class GradeElementaryUpdateResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: GradeElementary
