"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .gradeelementarylist import GradeElementaryList, GradeElementaryListTypedDict
from meitner.types import BaseModel, UNSET_SENTINEL
from meitner.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Awaitable, Callable, Dict, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class GradeElementaryListRequestTypedDict(TypedDict):
    limit: NotRequired[int]
    r"""The maximum number of GradeElementaries to return (default: 50) when listing GradeElementaries"""
    offset: NotRequired[int]
    r"""The number of GradeElementaries to skip before starting to return results (default: 0) when listing GradeElementaries"""


class GradeElementaryListRequest(BaseModel):
    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 50
    r"""The maximum number of GradeElementaries to return (default: 50) when listing GradeElementaries"""

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0
    r"""The number of GradeElementaries to skip before starting to return results (default: 0) when listing GradeElementaries"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["limit", "offset"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GradeElementaryListResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: GradeElementaryListTypedDict


class GradeElementaryListResponse(BaseModel):
    next: Union[
        Callable[[], Optional[GradeElementaryListResponse]],
        Callable[[], Awaitable[Optional[GradeElementaryListResponse]]],
    ]

    headers: Dict[str, List[str]]

    result: GradeElementaryList
