"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date, datetime
from meitner.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GradeUpperSecondaryMetaTypedDict(TypedDict):
    r"""Metadata information for the GradeUpperSecondary"""

    created_at: datetime
    r"""Timestamp when the resource was created"""
    created_by: NotRequired[Nullable[str]]
    r"""User who created the resource"""
    updated_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was last updated"""
    updated_by: NotRequired[Nullable[str]]
    r"""User who last updated the resource"""


class GradeUpperSecondaryMeta(BaseModel):
    r"""Metadata information for the GradeUpperSecondary"""

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]
    r"""Timestamp when the resource was created"""

    created_by: Annotated[OptionalNullable[str], pydantic.Field(alias="createdBy")] = (
        UNSET
    )
    r"""User who created the resource"""

    updated_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="updatedAt")
    ] = UNSET
    r"""Timestamp when the resource was last updated"""

    updated_by: Annotated[OptionalNullable[str], pydantic.Field(alias="updatedBy")] = (
        UNSET
    )
    r"""User who last updated the resource"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdBy", "updatedAt", "updatedBy"])
        nullable_fields = set(["createdBy", "updatedAt", "updatedBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class GradeUpperSecondaryExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the grade from another system, used for third-party integration tracking."""

    source_id: NotRequired[Nullable[str]]
    r"""The ID of the external source"""
    source: NotRequired[Nullable[str]]
    r"""The source of the external information"""


class GradeUpperSecondaryExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the grade from another system, used for third-party integration tracking."""

    source_id: Annotated[OptionalNullable[str], pydantic.Field(alias="sourceID")] = (
        UNSET
    )
    r"""The ID of the external source"""

    source: OptionalNullable[str] = UNSET
    r"""The source of the external information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sourceID", "source"])
        nullable_fields = set(["sourceID", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


GradeUpperSecondaryGrade = Literal[
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "MISSING",
]
r"""The grade awarded to the student."""


GradeUpperSecondaryExtent = Literal[
    "Normal",
    "Extended",
    "Reduced",
]
r"""The extent of the course for this student."""


GradeUpperSecondarySchoolYear = Literal[
    "1",
    "2",
    "3",
]
r"""The school year of the student at the time the grade was awarded."""


GradeUpperSecondarySection = Literal[
    "General",
    "Program",
    "Orientation",
    "Specialization",
    "Individual",
    "Project",
    "Elementary",
]
r"""The section/type of the course in the student's study plan."""


class GradeUpperSecondaryTypedDict(TypedDict):
    r"""GradeUpperSecondary represents a grade awarded to a student in upper secondary school (Swedish: gymnasieskola).
    Grades are scoped to the organization of the API key used. The CourseCode field uses the national course code as defined by the Swedish school authorities (e.g. \"MATMAT01a\").

    """

    id: str
    r"""Unique identifier for the GradeUpperSecondary"""
    student_id: str
    r"""The ID of the student the grade belongs to. Must reference a student within the organization who has an active placement at the school referenced by SchoolID."""
    school_id: str
    r"""The ID of the school where the student received the grade. Must reference a school within the organization."""
    course_code: str
    r"""The national course code as defined by the Swedish school authorities (e.g. \"MATMAT01a\" for Mathematics 1a)."""
    include_on_final_grade: bool
    r"""Whether this course grade should be included when calculating the student's final grade certificate."""
    meta: NotRequired[GradeUpperSecondaryMetaTypedDict]
    r"""Metadata information for the GradeUpperSecondary"""
    external: NotRequired[Nullable[GradeUpperSecondaryExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the grade from another system, used for third-party integration tracking."""
    language_code: NotRequired[Nullable[str]]
    r"""The language code for the grade, used when the course is taught in a specific language."""
    teacher1_employee_id: NotRequired[Nullable[str]]
    r"""The ID of the primary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID."""
    teacher2_employee_id: NotRequired[Nullable[str]]
    r"""The ID of the secondary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID."""
    grade: NotRequired[Nullable[GradeUpperSecondaryGrade]]
    r"""The grade awarded to the student."""
    grade_date: NotRequired[Nullable[date]]
    r"""The date the grade was awarded."""
    grade_comment: NotRequired[Nullable[str]]
    r"""A comment about the grade from the teacher."""
    extent: NotRequired[Nullable[GradeUpperSecondaryExtent]]
    r"""The extent of the course for this student."""
    school_year: NotRequired[Nullable[GradeUpperSecondarySchoolYear]]
    r"""The school year of the student at the time the grade was awarded."""
    section: NotRequired[Nullable[GradeUpperSecondarySection]]
    r"""The section/type of the course in the student's study plan."""
    teacher_comment: NotRequired[Nullable[str]]
    r"""A comment from the teacher about the student's performance."""
    program_title: NotRequired[Nullable[str]]
    r"""The title of the program this course belongs to. Used to associate the course with a specific educational program."""
    start_date: NotRequired[Nullable[date]]
    r"""The date the student started the course."""
    end_date: NotRequired[Nullable[date]]
    r"""The date the student finished the course."""


class GradeUpperSecondary(BaseModel):
    r"""GradeUpperSecondary represents a grade awarded to a student in upper secondary school (Swedish: gymnasieskola).
    Grades are scoped to the organization of the API key used. The CourseCode field uses the national course code as defined by the Swedish school authorities (e.g. \"MATMAT01a\").

    """

    id: str
    r"""Unique identifier for the GradeUpperSecondary"""

    student_id: Annotated[str, pydantic.Field(alias="studentID")]
    r"""The ID of the student the grade belongs to. Must reference a student within the organization who has an active placement at the school referenced by SchoolID."""

    school_id: Annotated[str, pydantic.Field(alias="schoolID")]
    r"""The ID of the school where the student received the grade. Must reference a school within the organization."""

    course_code: Annotated[str, pydantic.Field(alias="courseCode")]
    r"""The national course code as defined by the Swedish school authorities (e.g. \"MATMAT01a\" for Mathematics 1a)."""

    include_on_final_grade: Annotated[bool, pydantic.Field(alias="includeOnFinalGrade")]
    r"""Whether this course grade should be included when calculating the student's final grade certificate."""

    meta: Optional[GradeUpperSecondaryMeta] = None
    r"""Metadata information for the GradeUpperSecondary"""

    external: OptionalNullable[GradeUpperSecondaryExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the grade from another system, used for third-party integration tracking."""

    language_code: Annotated[
        OptionalNullable[str], pydantic.Field(alias="languageCode")
    ] = UNSET
    r"""The language code for the grade, used when the course is taught in a specific language."""

    teacher1_employee_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="teacher1EmployeeID")
    ] = UNSET
    r"""The ID of the primary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID."""

    teacher2_employee_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="teacher2EmployeeID")
    ] = UNSET
    r"""The ID of the secondary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID."""

    grade: OptionalNullable[GradeUpperSecondaryGrade] = UNSET
    r"""The grade awarded to the student."""

    grade_date: Annotated[OptionalNullable[date], pydantic.Field(alias="gradeDate")] = (
        UNSET
    )
    r"""The date the grade was awarded."""

    grade_comment: Annotated[
        OptionalNullable[str], pydantic.Field(alias="gradeComment")
    ] = UNSET
    r"""A comment about the grade from the teacher."""

    extent: OptionalNullable[GradeUpperSecondaryExtent] = UNSET
    r"""The extent of the course for this student."""

    school_year: Annotated[
        OptionalNullable[GradeUpperSecondarySchoolYear],
        pydantic.Field(alias="schoolYear"),
    ] = UNSET
    r"""The school year of the student at the time the grade was awarded."""

    section: OptionalNullable[GradeUpperSecondarySection] = UNSET
    r"""The section/type of the course in the student's study plan."""

    teacher_comment: Annotated[
        OptionalNullable[str], pydantic.Field(alias="teacherComment")
    ] = UNSET
    r"""A comment from the teacher about the student's performance."""

    program_title: Annotated[
        OptionalNullable[str], pydantic.Field(alias="programTitle")
    ] = UNSET
    r"""The title of the program this course belongs to. Used to associate the course with a specific educational program."""

    start_date: Annotated[OptionalNullable[date], pydantic.Field(alias="startDate")] = (
        UNSET
    )
    r"""The date the student started the course."""

    end_date: Annotated[OptionalNullable[date], pydantic.Field(alias="endDate")] = UNSET
    r"""The date the student finished the course."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "meta",
                "external",
                "languageCode",
                "teacher1EmployeeID",
                "teacher2EmployeeID",
                "grade",
                "gradeDate",
                "gradeComment",
                "extent",
                "schoolYear",
                "section",
                "teacherComment",
                "programTitle",
                "startDate",
                "endDate",
            ]
        )
        nullable_fields = set(
            [
                "external",
                "languageCode",
                "teacher1EmployeeID",
                "teacher2EmployeeID",
                "grade",
                "gradeDate",
                "gradeComment",
                "extent",
                "schoolYear",
                "section",
                "teacherComment",
                "programTitle",
                "startDate",
                "endDate",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    GradeUpperSecondaryMeta.model_rebuild()
except NameError:
    pass
try:
    GradeUpperSecondaryExternal.model_rebuild()
except NameError:
    pass
try:
    GradeUpperSecondary.model_rebuild()
except NameError:
    pass
