"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date
from meitner.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GradeUpperSecondaryUpdateExternalTypedDict(TypedDict):
    r"""ExternalRequest is the External-object used on Create and Update operations. Only SourceID can be set — the Source field is derived from the API key."""

    source_id: str
    r"""The ID of the external source"""


class GradeUpperSecondaryUpdateExternal(BaseModel):
    r"""ExternalRequest is the External-object used on Create and Update operations. Only SourceID can be set — the Source field is derived from the API key."""

    source_id: Annotated[str, pydantic.Field(alias="sourceID")]
    r"""The ID of the external source"""


GradeUpperSecondaryUpdateGrade = Literal[
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "MISSING",
]
r"""The grade awarded to the student."""


GradeUpperSecondaryUpdateExtent = Literal[
    "Normal",
    "Extended",
    "Reduced",
]
r"""The extent of the course for this student."""


GradeUpperSecondaryUpdateSchoolYear = Literal[
    "1",
    "2",
    "3",
]
r"""The school year of the student at the time the grade was awarded."""


GradeUpperSecondaryUpdateSection = Literal[
    "General",
    "Program",
    "Orientation",
    "Specialization",
    "Individual",
    "Project",
    "Elementary",
]
r"""The section/type of the course in the student's study plan."""


class GradeUpperSecondaryUpdateTypedDict(TypedDict):
    r"""Request body"""

    include_on_final_grade: bool
    r"""Whether this course grade should be included when calculating the student's final grade certificate."""
    external: NotRequired[GradeUpperSecondaryUpdateExternalTypedDict]
    r"""ExternalRequest is the External-object used on Create and Update operations. Only SourceID can be set — the Source field is derived from the API key."""
    language_code: NotRequired[Nullable[str]]
    r"""The language code for the grade, used when the course is taught in a specific language."""
    teacher1_employee_id: NotRequired[Nullable[str]]
    r"""The ID of the primary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID."""
    teacher2_employee_id: NotRequired[Nullable[str]]
    r"""The ID of the secondary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID."""
    grade: NotRequired[Nullable[GradeUpperSecondaryUpdateGrade]]
    r"""The grade awarded to the student."""
    grade_date: NotRequired[Nullable[date]]
    r"""The date the grade was awarded."""
    grade_comment: NotRequired[Nullable[str]]
    r"""A comment about the grade from the teacher."""
    extent: NotRequired[Nullable[GradeUpperSecondaryUpdateExtent]]
    r"""The extent of the course for this student."""
    school_year: NotRequired[Nullable[GradeUpperSecondaryUpdateSchoolYear]]
    r"""The school year of the student at the time the grade was awarded."""
    section: NotRequired[Nullable[GradeUpperSecondaryUpdateSection]]
    r"""The section/type of the course in the student's study plan."""
    teacher_comment: NotRequired[Nullable[str]]
    r"""A comment from the teacher about the student's performance."""
    program_title: NotRequired[Nullable[str]]
    r"""The title of the program this course belongs to. Used to associate the course with a specific educational program."""
    start_date: NotRequired[Nullable[date]]
    r"""The date the student started the course."""
    end_date: NotRequired[Nullable[date]]
    r"""The date the student finished the course."""


class GradeUpperSecondaryUpdate(BaseModel):
    r"""Request body"""

    include_on_final_grade: Annotated[bool, pydantic.Field(alias="includeOnFinalGrade")]
    r"""Whether this course grade should be included when calculating the student's final grade certificate."""

    external: Optional[GradeUpperSecondaryUpdateExternal] = None
    r"""ExternalRequest is the External-object used on Create and Update operations. Only SourceID can be set — the Source field is derived from the API key."""

    language_code: Annotated[
        OptionalNullable[str], pydantic.Field(alias="languageCode")
    ] = UNSET
    r"""The language code for the grade, used when the course is taught in a specific language."""

    teacher1_employee_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="teacher1EmployeeID")
    ] = UNSET
    r"""The ID of the primary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID."""

    teacher2_employee_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="teacher2EmployeeID")
    ] = UNSET
    r"""The ID of the secondary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID."""

    grade: OptionalNullable[GradeUpperSecondaryUpdateGrade] = UNSET
    r"""The grade awarded to the student."""

    grade_date: Annotated[OptionalNullable[date], pydantic.Field(alias="gradeDate")] = (
        UNSET
    )
    r"""The date the grade was awarded."""

    grade_comment: Annotated[
        OptionalNullable[str], pydantic.Field(alias="gradeComment")
    ] = UNSET
    r"""A comment about the grade from the teacher."""

    extent: OptionalNullable[GradeUpperSecondaryUpdateExtent] = UNSET
    r"""The extent of the course for this student."""

    school_year: Annotated[
        OptionalNullable[GradeUpperSecondaryUpdateSchoolYear],
        pydantic.Field(alias="schoolYear"),
    ] = UNSET
    r"""The school year of the student at the time the grade was awarded."""

    section: OptionalNullable[GradeUpperSecondaryUpdateSection] = UNSET
    r"""The section/type of the course in the student's study plan."""

    teacher_comment: Annotated[
        OptionalNullable[str], pydantic.Field(alias="teacherComment")
    ] = UNSET
    r"""A comment from the teacher about the student's performance."""

    program_title: Annotated[
        OptionalNullable[str], pydantic.Field(alias="programTitle")
    ] = UNSET
    r"""The title of the program this course belongs to. Used to associate the course with a specific educational program."""

    start_date: Annotated[OptionalNullable[date], pydantic.Field(alias="startDate")] = (
        UNSET
    )
    r"""The date the student started the course."""

    end_date: Annotated[OptionalNullable[date], pydantic.Field(alias="endDate")] = UNSET
    r"""The date the student finished the course."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "external",
                "languageCode",
                "teacher1EmployeeID",
                "teacher2EmployeeID",
                "grade",
                "gradeDate",
                "gradeComment",
                "extent",
                "schoolYear",
                "section",
                "teacherComment",
                "programTitle",
                "startDate",
                "endDate",
            ]
        )
        nullable_fields = set(
            [
                "languageCode",
                "teacher1EmployeeID",
                "teacher2EmployeeID",
                "grade",
                "gradeDate",
                "gradeComment",
                "extent",
                "schoolYear",
                "section",
                "teacherComment",
                "programTitle",
                "startDate",
                "endDate",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    GradeUpperSecondaryUpdateExternal.model_rebuild()
except NameError:
    pass
try:
    GradeUpperSecondaryUpdate.model_rebuild()
except NameError:
    pass
