"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .gradeuppersecondary import GradeUpperSecondary, GradeUpperSecondaryTypedDict
from meitner.types import BaseModel
from typing import Dict, List
from typing_extensions import TypedDict


class GradeUpperSecondaryCreateResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: GradeUpperSecondaryTypedDict


class GradeUpperSecondaryCreateResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: GradeUpperSecondary
