"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date
from meitner.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GradeElementaryUpdateExternalTypedDict(TypedDict):
    r"""ExternalRequest is the External-object used on Create and Update operations. Only SourceID can be set — the Source field is derived from the API key."""

    source_id: str
    r"""The ID of the external source"""


class GradeElementaryUpdateExternal(BaseModel):
    r"""ExternalRequest is the External-object used on Create and Update operations. Only SourceID can be set — the Source field is derived from the API key."""

    source_id: Annotated[str, pydantic.Field(alias="sourceID")]
    r"""The ID of the external source"""


GradeElementaryUpdateTerm = Literal[
    "HT",
    "VT",
]
r"""The school term in which the grade was awarded."""


GradeElementaryUpdateSchoolYear = Literal[
    "6",
    "7",
    "8",
    "9",
]
r"""The school year of the student at the time the grade was awarded."""


GradeElementaryUpdateGrade = Literal[
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "MISSING",
]
r"""The grade awarded to the student."""


class GradeElementaryUpdateTypedDict(TypedDict):
    r"""Request body"""

    academic_year: str
    r"""The academic year in which the grade was awarded, in the format YYYY/YYYY (e.g. \"2024/2025\")."""
    term: GradeElementaryUpdateTerm
    r"""The school term in which the grade was awarded."""
    school_year: GradeElementaryUpdateSchoolYear
    r"""The school year of the student at the time the grade was awarded."""
    final_grade: bool
    r"""Whether this is the final grade for the student in this subject. A final grade is the official grade used on the student's grade certificate."""
    is_ended: bool
    r"""Whether the grading period has ended for this student in this subject."""
    external: NotRequired[GradeElementaryUpdateExternalTypedDict]
    r"""ExternalRequest is the External-object used on Create and Update operations. Only SourceID can be set — the Source field is derived from the API key."""
    language_code: NotRequired[Nullable[str]]
    r"""The language code for the grade, used when the subject is taught in a specific language (e.g. mother tongue instruction)."""
    teacher1_employee_id: NotRequired[Nullable[str]]
    r"""The ID of the primary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID."""
    teacher2_employee_id: NotRequired[Nullable[str]]
    r"""The ID of the secondary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID."""
    grade: NotRequired[Nullable[GradeElementaryUpdateGrade]]
    r"""The grade awarded to the student."""
    grade_date: NotRequired[Nullable[date]]
    r"""The date the grade was awarded."""
    school_comment: NotRequired[Nullable[str]]
    r"""A comment from the school about the grade, visible to the student and guardians."""


class GradeElementaryUpdate(BaseModel):
    r"""Request body"""

    academic_year: Annotated[str, pydantic.Field(alias="academicYear")]
    r"""The academic year in which the grade was awarded, in the format YYYY/YYYY (e.g. \"2024/2025\")."""

    term: GradeElementaryUpdateTerm
    r"""The school term in which the grade was awarded."""

    school_year: Annotated[
        GradeElementaryUpdateSchoolYear, pydantic.Field(alias="schoolYear")
    ]
    r"""The school year of the student at the time the grade was awarded."""

    final_grade: Annotated[bool, pydantic.Field(alias="finalGrade")]
    r"""Whether this is the final grade for the student in this subject. A final grade is the official grade used on the student's grade certificate."""

    is_ended: Annotated[bool, pydantic.Field(alias="isEnded")]
    r"""Whether the grading period has ended for this student in this subject."""

    external: Optional[GradeElementaryUpdateExternal] = None
    r"""ExternalRequest is the External-object used on Create and Update operations. Only SourceID can be set — the Source field is derived from the API key."""

    language_code: Annotated[
        OptionalNullable[str], pydantic.Field(alias="languageCode")
    ] = UNSET
    r"""The language code for the grade, used when the subject is taught in a specific language (e.g. mother tongue instruction)."""

    teacher1_employee_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="teacher1EmployeeID")
    ] = UNSET
    r"""The ID of the primary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID."""

    teacher2_employee_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="teacher2EmployeeID")
    ] = UNSET
    r"""The ID of the secondary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID."""

    grade: OptionalNullable[GradeElementaryUpdateGrade] = UNSET
    r"""The grade awarded to the student."""

    grade_date: Annotated[OptionalNullable[date], pydantic.Field(alias="gradeDate")] = (
        UNSET
    )
    r"""The date the grade was awarded."""

    school_comment: Annotated[
        OptionalNullable[str], pydantic.Field(alias="schoolComment")
    ] = UNSET
    r"""A comment from the school about the grade, visible to the student and guardians."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "external",
                "languageCode",
                "teacher1EmployeeID",
                "teacher2EmployeeID",
                "grade",
                "gradeDate",
                "schoolComment",
            ]
        )
        nullable_fields = set(
            [
                "languageCode",
                "teacher1EmployeeID",
                "teacher2EmployeeID",
                "grade",
                "gradeDate",
                "schoolComment",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    GradeElementaryUpdateExternal.model_rebuild()
except NameError:
    pass
try:
    GradeElementaryUpdate.model_rebuild()
except NameError:
    pass
