"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date, datetime
from meitner.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GradeElementaryMetaTypedDict(TypedDict):
    r"""Metadata information for the GradeElementary"""

    created_at: datetime
    r"""Timestamp when the resource was created"""
    created_by: NotRequired[Nullable[str]]
    r"""User who created the resource"""
    updated_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was last updated"""
    updated_by: NotRequired[Nullable[str]]
    r"""User who last updated the resource"""


class GradeElementaryMeta(BaseModel):
    r"""Metadata information for the GradeElementary"""

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]
    r"""Timestamp when the resource was created"""

    created_by: Annotated[OptionalNullable[str], pydantic.Field(alias="createdBy")] = (
        UNSET
    )
    r"""User who created the resource"""

    updated_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="updatedAt")
    ] = UNSET
    r"""Timestamp when the resource was last updated"""

    updated_by: Annotated[OptionalNullable[str], pydantic.Field(alias="updatedBy")] = (
        UNSET
    )
    r"""User who last updated the resource"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdBy", "updatedAt", "updatedBy"])
        nullable_fields = set(["createdBy", "updatedAt", "updatedBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class GradeElementaryExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the grade from another system, used for third-party integration tracking."""

    source_id: NotRequired[Nullable[str]]
    r"""The ID of the external source"""
    source: NotRequired[Nullable[str]]
    r"""The source of the external information"""


class GradeElementaryExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the grade from another system, used for third-party integration tracking."""

    source_id: Annotated[OptionalNullable[str], pydantic.Field(alias="sourceID")] = (
        UNSET
    )
    r"""The ID of the external source"""

    source: OptionalNullable[str] = UNSET
    r"""The source of the external information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sourceID", "source"])
        nullable_fields = set(["sourceID", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


GradeElementaryTerm = Literal[
    "HT",
    "VT",
]
r"""The school term in which the grade was awarded."""


GradeElementarySchoolYear = Literal[
    "6",
    "7",
    "8",
    "9",
]
r"""The school year of the student at the time the grade was awarded."""


GradeElementaryGrade = Literal[
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "MISSING",
]
r"""The grade awarded to the student."""


class GradeElementaryTypedDict(TypedDict):
    r"""GradeElementary represents a grade awarded to a student in elementary school (Swedish: grundskola).
    Grades are scoped to the organization of the API key used. The SubjectCode field uses the subject code as defined by the Swedish school authorities (e.g. \"MA\" for Mathematics).

    """

    id: str
    r"""Unique identifier for the GradeElementary"""
    student_id: str
    r"""The ID of the student the grade belongs to. Must reference a student within the organization who has an active placement at the school referenced by SchoolID."""
    school_id: str
    r"""The ID of the school where the student received the grade. Must reference a school within the organization."""
    subject_code: str
    r"""The subject code as defined by the Swedish school authorities (e.g. \"MA\" for Mathematics, \"SV\" for Swedish)."""
    academic_year: str
    r"""The academic year in which the grade was awarded, in the format YYYY/YYYY (e.g. \"2024/2025\")."""
    term: GradeElementaryTerm
    r"""The school term in which the grade was awarded."""
    school_year: GradeElementarySchoolYear
    r"""The school year of the student at the time the grade was awarded."""
    final_grade: bool
    r"""Whether this is the final grade for the student in this subject. A final grade is the official grade used on the student's grade certificate."""
    is_ended: bool
    r"""Whether the grading period has ended for this student in this subject."""
    meta: NotRequired[GradeElementaryMetaTypedDict]
    r"""Metadata information for the GradeElementary"""
    external: NotRequired[Nullable[GradeElementaryExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the grade from another system, used for third-party integration tracking."""
    language_code: NotRequired[Nullable[str]]
    r"""The language code for the grade, used when the subject is taught in a specific language (e.g. mother tongue instruction)."""
    teacher1_employee_id: NotRequired[Nullable[str]]
    r"""The ID of the primary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID."""
    teacher2_employee_id: NotRequired[Nullable[str]]
    r"""The ID of the secondary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID."""
    grade: NotRequired[Nullable[GradeElementaryGrade]]
    r"""The grade awarded to the student."""
    grade_date: NotRequired[Nullable[date]]
    r"""The date the grade was awarded."""
    school_comment: NotRequired[Nullable[str]]
    r"""A comment from the school about the grade, visible to the student and guardians."""


class GradeElementary(BaseModel):
    r"""GradeElementary represents a grade awarded to a student in elementary school (Swedish: grundskola).
    Grades are scoped to the organization of the API key used. The SubjectCode field uses the subject code as defined by the Swedish school authorities (e.g. \"MA\" for Mathematics).

    """

    id: str
    r"""Unique identifier for the GradeElementary"""

    student_id: Annotated[str, pydantic.Field(alias="studentID")]
    r"""The ID of the student the grade belongs to. Must reference a student within the organization who has an active placement at the school referenced by SchoolID."""

    school_id: Annotated[str, pydantic.Field(alias="schoolID")]
    r"""The ID of the school where the student received the grade. Must reference a school within the organization."""

    subject_code: Annotated[str, pydantic.Field(alias="subjectCode")]
    r"""The subject code as defined by the Swedish school authorities (e.g. \"MA\" for Mathematics, \"SV\" for Swedish)."""

    academic_year: Annotated[str, pydantic.Field(alias="academicYear")]
    r"""The academic year in which the grade was awarded, in the format YYYY/YYYY (e.g. \"2024/2025\")."""

    term: GradeElementaryTerm
    r"""The school term in which the grade was awarded."""

    school_year: Annotated[
        GradeElementarySchoolYear, pydantic.Field(alias="schoolYear")
    ]
    r"""The school year of the student at the time the grade was awarded."""

    final_grade: Annotated[bool, pydantic.Field(alias="finalGrade")]
    r"""Whether this is the final grade for the student in this subject. A final grade is the official grade used on the student's grade certificate."""

    is_ended: Annotated[bool, pydantic.Field(alias="isEnded")]
    r"""Whether the grading period has ended for this student in this subject."""

    meta: Optional[GradeElementaryMeta] = None
    r"""Metadata information for the GradeElementary"""

    external: OptionalNullable[GradeElementaryExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the grade from another system, used for third-party integration tracking."""

    language_code: Annotated[
        OptionalNullable[str], pydantic.Field(alias="languageCode")
    ] = UNSET
    r"""The language code for the grade, used when the subject is taught in a specific language (e.g. mother tongue instruction)."""

    teacher1_employee_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="teacher1EmployeeID")
    ] = UNSET
    r"""The ID of the primary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID."""

    teacher2_employee_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="teacher2EmployeeID")
    ] = UNSET
    r"""The ID of the secondary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID."""

    grade: OptionalNullable[GradeElementaryGrade] = UNSET
    r"""The grade awarded to the student."""

    grade_date: Annotated[OptionalNullable[date], pydantic.Field(alias="gradeDate")] = (
        UNSET
    )
    r"""The date the grade was awarded."""

    school_comment: Annotated[
        OptionalNullable[str], pydantic.Field(alias="schoolComment")
    ] = UNSET
    r"""A comment from the school about the grade, visible to the student and guardians."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "meta",
                "external",
                "languageCode",
                "teacher1EmployeeID",
                "teacher2EmployeeID",
                "grade",
                "gradeDate",
                "schoolComment",
            ]
        )
        nullable_fields = set(
            [
                "external",
                "languageCode",
                "teacher1EmployeeID",
                "teacher2EmployeeID",
                "grade",
                "gradeDate",
                "schoolComment",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    GradeElementaryMeta.model_rebuild()
except NameError:
    pass
try:
    GradeElementaryExternal.model_rebuild()
except NameError:
    pass
try:
    GradeElementary.model_rebuild()
except NameError:
    pass
