"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .gradeelementary import GradeElementary, GradeElementaryTypedDict
from meitner.types import BaseModel
from typing import Dict, List
from typing_extensions import TypedDict


class GradeElementaryCreateResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: GradeElementaryTypedDict


class GradeElementaryCreateResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: GradeElementary
