"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .gradeuppersecondary import GradeUpperSecondary, GradeUpperSecondaryTypedDict
from .gradeuppersecondaryupdate import (
    GradeUpperSecondaryUpdate,
    GradeUpperSecondaryUpdateTypedDict,
)
from meitner.types import BaseModel
from meitner.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class GradeUpperSecondaryUpdateRequestTypedDict(TypedDict):
    id: str
    r"""The unique identifier of the GradeUpperSecondary to update"""
    grade_upper_secondary_update: GradeUpperSecondaryUpdateTypedDict
    r"""Request body"""


class GradeUpperSecondaryUpdateRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The unique identifier of the GradeUpperSecondary to update"""

    grade_upper_secondary_update: Annotated[
        GradeUpperSecondaryUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Request body"""


class GradeUpperSecondaryUpdateResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: GradeUpperSecondaryTypedDict


class GradeUpperSecondaryUpdateResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: GradeUpperSecondary
