"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from meitner.types import BaseModel
from meitner.utils import FieldMetadata, PathParamMetadata
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class GradeElementaryDeleteRequestTypedDict(TypedDict):
    id: str
    r"""The unique identifier of the GradeElementary to delete"""


class GradeElementaryDeleteRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The unique identifier of the GradeElementary to delete"""


class GradeElementaryDeleteResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]


class GradeElementaryDeleteResponse(BaseModel):
    headers: Dict[str, List[str]]
