"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .gradeuppersecondary import GradeUpperSecondary, GradeUpperSecondaryTypedDict
from meitner.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class GradeUpperSecondaryListPaginationTypedDict(TypedDict):
    r"""Pagination information"""

    offset: int
    r"""Number of items to skip from the beginning of the result set"""
    limit: int
    r"""Maximum number of items to return in the result set"""
    total: int
    r"""Total number of items available for pagination"""


class GradeUpperSecondaryListPagination(BaseModel):
    r"""Pagination information"""

    offset: int
    r"""Number of items to skip from the beginning of the result set"""

    limit: int
    r"""Maximum number of items to return in the result set"""

    total: int
    r"""Total number of items available for pagination"""


class GradeUpperSecondaryListTypedDict(TypedDict):
    r"""Response for GradeUpperSecondary List operation - returns a paginated list of GradeUpperSecondary"""

    data: NotRequired[List[GradeUpperSecondaryTypedDict]]
    r"""Array of GradeUpperSecondary objects"""
    pagination: NotRequired[GradeUpperSecondaryListPaginationTypedDict]
    r"""Pagination information"""


class GradeUpperSecondaryList(BaseModel):
    r"""Response for GradeUpperSecondary List operation - returns a paginated list of GradeUpperSecondary"""

    data: Optional[List[GradeUpperSecondary]] = None
    r"""Array of GradeUpperSecondary objects"""

    pagination: Optional[GradeUpperSecondaryListPagination] = None
    r"""Pagination information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data", "pagination"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
