"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


ModernLanguageAlternative = Literal[
    "EN",
    "ML",
    "SV",
    "SVA",
    "TN",
]
r"""The modern language alternative for the student"""
