"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from meitner.types import BaseModel, UNSET_SENTINEL
from meitner.utils import FieldMetadata, SecurityMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SecurityOption1TypedDict(TypedDict):
    client_credentials: str
    client_secret: str


class SecurityOption1(BaseModel):
    client_credentials: Annotated[
        str,
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                composite=True,
                field_name="Client-ID",
            )
        ),
    ]

    client_secret: Annotated[
        str,
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                composite=True,
                field_name="Client-Secret",
            )
        ),
    ]


class SecurityOption2TypedDict(TypedDict):
    client_id: str
    client_secret: str
    token_url: str


class SecurityOption2(BaseModel):
    client_id: Annotated[
        str,
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="oauth2",
                sub_type="client_credentials",
                field_name="clientID",
            )
        ),
    ]

    client_secret: Annotated[
        str,
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="oauth2",
                sub_type="client_credentials",
                field_name="clientSecret",
            )
        ),
    ]

    token_url: str = "/oauth/token"


class SecurityTypedDict(TypedDict):
    option1: NotRequired[SecurityOption1TypedDict]
    option2: NotRequired[SecurityOption2TypedDict]


class Security(BaseModel):
    option1: Annotated[
        Optional[SecurityOption1], FieldMetadata(security=SecurityMetadata(option=True))
    ] = None

    option2: Annotated[
        Optional[SecurityOption2], FieldMetadata(security=SecurityMetadata(option=True))
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["Option1", "Option2"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
