"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


StudentPlacementSchoolType = Literal[
    "GR",
    "GRAN",
    "GY",
    "GYAN",
    "FS",
    "VUX",
    "VUXSFI",
]
r"""The type of schooling the student is attending"""
