"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date
from meitner.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class StudentPlacementUpdateExternalTypedDict(TypedDict):
    r"""ExternalRequest is the External-object used on Update and Create operations, since it should only be allowed to set SourceID for the student placement, the Source-field is not included."""

    source_id: str
    r"""The ID of the external source"""


class StudentPlacementUpdateExternal(BaseModel):
    r"""ExternalRequest is the External-object used on Update and Create operations, since it should only be allowed to set SourceID for the student placement, the Source-field is not included."""

    source_id: Annotated[str, pydantic.Field(alias="sourceID")]
    r"""The ID of the external source"""


StudentPlacementUpdateSchoolType = Literal[
    "GR",
    "GRAN",
    "GY",
    "GYAN",
    "FS",
]
r"""The school type for the student, if not provided on Create, the school type will be fetched from the school."""


StudentPlacementUpdateSchoolYear = Literal[
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
]
r"""The school year the student is placed in"""


StudentPlacementUpdateModernLanguageAlternative = Literal[
    "EN",
    "ML",
    "SV",
    "SVA",
    "TN",
]
r"""The modern language alternative for the student"""


class StudentPlacementUpdateTypedDict(TypedDict):
    r"""Request body"""

    school_type: StudentPlacementUpdateSchoolType
    r"""The school type for the student, if not provided on Create, the school type will be fetched from the school."""
    start_date: date
    r"""The start date of the placement"""
    external: NotRequired[StudentPlacementUpdateExternalTypedDict]
    r"""ExternalRequest is the External-object used on Update and Create operations, since it should only be allowed to set SourceID for the student placement, the Source-field is not included."""
    school_year: NotRequired[Nullable[StudentPlacementUpdateSchoolYear]]
    r"""The school year the student is placed in"""
    has_childcare: NotRequired[bool]
    r"""Whether the student has childcare"""
    mother_tongue: NotRequired[Nullable[str]]
    r"""The mother tongue of the student. Language codes follow the ISO 639-3 standard (three-letter codes)."""
    modern_language_alternative: NotRequired[
        Nullable[StudentPlacementUpdateModernLanguageAlternative]
    ]
    r"""The modern language alternative for the student"""
    swedish_as_second_language: NotRequired[bool]
    r"""Whether the student has Swedish as their second language"""
    mother_tongue_participates: NotRequired[bool]
    r"""Whether the student participates in mother tongue education"""
    modern_language_in_school_choice: NotRequired[Nullable[str]]
    r"""The language code for the student's modern language in school choice (Skolans val). Language codes follow the ISO 639-2 standard (three-letter codes)."""
    modern_language_in_language_choice: NotRequired[Nullable[str]]
    r"""The language code for the student's modern language in language choice (Språkval, M2, B-språk). Language codes follow the ISO 639-2 standard (three-letter codes)."""
    end_date: NotRequired[Nullable[date]]
    r"""The end date of the placement"""


class StudentPlacementUpdate(BaseModel):
    r"""Request body"""

    school_type: Annotated[
        StudentPlacementUpdateSchoolType, pydantic.Field(alias="schoolType")
    ]
    r"""The school type for the student, if not provided on Create, the school type will be fetched from the school."""

    start_date: Annotated[date, pydantic.Field(alias="startDate")]
    r"""The start date of the placement"""

    external: Optional[StudentPlacementUpdateExternal] = None
    r"""ExternalRequest is the External-object used on Update and Create operations, since it should only be allowed to set SourceID for the student placement, the Source-field is not included."""

    school_year: Annotated[
        OptionalNullable[StudentPlacementUpdateSchoolYear],
        pydantic.Field(alias="schoolYear"),
    ] = UNSET
    r"""The school year the student is placed in"""

    has_childcare: Annotated[Optional[bool], pydantic.Field(alias="hasChildcare")] = (
        False
    )
    r"""Whether the student has childcare"""

    mother_tongue: Annotated[
        OptionalNullable[str], pydantic.Field(alias="motherTongue")
    ] = UNSET
    r"""The mother tongue of the student. Language codes follow the ISO 639-3 standard (three-letter codes)."""

    modern_language_alternative: Annotated[
        OptionalNullable[StudentPlacementUpdateModernLanguageAlternative],
        pydantic.Field(alias="modernLanguageAlternative"),
    ] = UNSET
    r"""The modern language alternative for the student"""

    swedish_as_second_language: Annotated[
        Optional[bool], pydantic.Field(alias="swedishAsSecondLanguage")
    ] = False
    r"""Whether the student has Swedish as their second language"""

    mother_tongue_participates: Annotated[
        Optional[bool], pydantic.Field(alias="motherTongueParticipates")
    ] = False
    r"""Whether the student participates in mother tongue education"""

    modern_language_in_school_choice: Annotated[
        OptionalNullable[str], pydantic.Field(alias="modernLanguageInSchoolChoice")
    ] = UNSET
    r"""The language code for the student's modern language in school choice (Skolans val). Language codes follow the ISO 639-2 standard (three-letter codes)."""

    modern_language_in_language_choice: Annotated[
        OptionalNullable[str], pydantic.Field(alias="modernLanguageInLanguageChoice")
    ] = UNSET
    r"""The language code for the student's modern language in language choice (Språkval, M2, B-språk). Language codes follow the ISO 639-2 standard (three-letter codes)."""

    end_date: Annotated[OptionalNullable[date], pydantic.Field(alias="endDate")] = UNSET
    r"""The end date of the placement"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "external",
                "schoolYear",
                "hasChildcare",
                "motherTongue",
                "modernLanguageAlternative",
                "swedishAsSecondLanguage",
                "motherTongueParticipates",
                "modernLanguageInSchoolChoice",
                "modernLanguageInLanguageChoice",
                "endDate",
            ]
        )
        nullable_fields = set(
            [
                "schoolYear",
                "motherTongue",
                "modernLanguageAlternative",
                "modernLanguageInSchoolChoice",
                "modernLanguageInLanguageChoice",
                "endDate",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    StudentPlacementUpdateExternal.model_rebuild()
except NameError:
    pass
try:
    StudentPlacementUpdate.model_rebuild()
except NameError:
    pass
