"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .unit import Unit, UnitTypedDict
from .unitupdate import UnitUpdate, UnitUpdateTypedDict
from meitner.types import BaseModel
from meitner.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class UnitUpdateRequestTypedDict(TypedDict):
    id: str
    r"""The unique identifier of the Unit to update"""
    unit_update: UnitUpdateTypedDict
    r"""Request body"""


class UnitUpdateRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The unique identifier of the Unit to update"""

    unit_update: Annotated[
        UnitUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Request body"""


class UnitUpdateResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: UnitTypedDict


class UnitUpdateResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: Unit
