"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from meitner.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UnitMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""

    created_at: datetime
    r"""Timestamp when the resource was created"""
    created_by: NotRequired[Nullable[str]]
    r"""User who created the resource"""
    updated_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was last updated"""
    updated_by: NotRequired[Nullable[str]]
    r"""User who last updated the resource"""


class UnitMeta(BaseModel):
    r"""Metadata information for the Unit"""

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]
    r"""Timestamp when the resource was created"""

    created_by: Annotated[OptionalNullable[str], pydantic.Field(alias="createdBy")] = (
        UNSET
    )
    r"""User who created the resource"""

    updated_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="updatedAt")
    ] = UNSET
    r"""Timestamp when the resource was last updated"""

    updated_by: Annotated[OptionalNullable[str], pydantic.Field(alias="updatedBy")] = (
        UNSET
    )
    r"""User who last updated the resource"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdBy", "updatedAt", "updatedBy"])
        nullable_fields = set(["createdBy", "updatedAt", "updatedBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: NotRequired[Nullable[str]]
    r"""The ID of the external source"""
    source: NotRequired[Nullable[str]]
    r"""The source of the external information"""


class UnitExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: Annotated[OptionalNullable[str], pydantic.Field(alias="sourceID")] = (
        UNSET
    )
    r"""The ID of the external source"""

    source: OptionalNullable[str] = UNSET
    r"""The source of the external information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sourceID", "source"])
        nullable_fields = set(["sourceID", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitTypedDict(TypedDict):
    r"""The `Unit` resource represents an organizational unit that schools can belong to.
    This resource can be created, updated, listed, retrieved, and searched using the standard resource structure.

    """

    id: str
    r"""Unique identifier for the Unit"""
    title: str
    r"""The title of the unit"""
    meta: NotRequired[UnitMetaTypedDict]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""
    description: NotRequired[Nullable[str]]
    r"""The description of the unit"""


class Unit(BaseModel):
    r"""The `Unit` resource represents an organizational unit that schools can belong to.
    This resource can be created, updated, listed, retrieved, and searched using the standard resource structure.

    """

    id: str
    r"""Unique identifier for the Unit"""

    title: str
    r"""The title of the unit"""

    meta: Optional[UnitMeta] = None
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    description: OptionalNullable[str] = UNSET
    r"""The description of the unit"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["meta", "external", "description"])
        nullable_fields = set(["external", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    UnitMeta.model_rebuild()
except NameError:
    pass
try:
    UnitExternal.model_rebuild()
except NameError:
    pass
