"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from meitner.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UnitCreateExternalTypedDict(TypedDict):
    r"""External is the External-object used on Update and Create operations, since it should only be allowed to set SourceID for the unit, the Source-field is not included."""

    source_id: str
    r"""The ID of the external source"""


class UnitCreateExternal(BaseModel):
    r"""External is the External-object used on Update and Create operations, since it should only be allowed to set SourceID for the unit, the Source-field is not included."""

    source_id: Annotated[str, pydantic.Field(alias="sourceID")]
    r"""The ID of the external source"""


class UnitCreateTypedDict(TypedDict):
    r"""Request body"""

    title: str
    r"""The title of the unit"""
    external: NotRequired[UnitCreateExternalTypedDict]
    r"""External is the External-object used on Update and Create operations, since it should only be allowed to set SourceID for the unit, the Source-field is not included."""
    description: NotRequired[Nullable[str]]
    r"""The description of the unit"""


class UnitCreate(BaseModel):
    r"""Request body"""

    title: str
    r"""The title of the unit"""

    external: Optional[UnitCreateExternal] = None
    r"""External is the External-object used on Update and Create operations, since it should only be allowed to set SourceID for the unit, the Source-field is not included."""

    description: OptionalNullable[str] = UNSET
    r"""The description of the unit"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["external", "description"])
        nullable_fields = set(["description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    UnitCreateExternal.model_rebuild()
except NameError:
    pass
