"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .unit import Unit, UnitTypedDict
from meitner.types import BaseModel
from meitner.utils import FieldMetadata, PathParamMetadata
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class UnitGetRequestTypedDict(TypedDict):
    id: str
    r"""The unique identifier of the Unit to retrieve"""


class UnitGetRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The unique identifier of the Unit to retrieve"""


class UnitGetResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: UnitTypedDict


class UnitGetResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: Unit
