"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .unit import Unit, UnitTypedDict
from meitner.types import BaseModel
from typing import Dict, List
from typing_extensions import TypedDict


class UnitCreateResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: UnitTypedDict


class UnitCreateResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: Unit
