"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .unitfilter import UnitFilter, UnitFilterTypedDict
from datetime import datetime
from meitner.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UnitSearchEqualsMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""

    created_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was created"""
    created_by: NotRequired[Nullable[str]]
    r"""User who created the resource"""
    updated_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was last updated"""
    updated_by: NotRequired[Nullable[str]]
    r"""User who last updated the resource"""


class UnitSearchEqualsMeta(BaseModel):
    r"""Metadata information for the Unit"""

    created_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="createdAt")
    ] = UNSET
    r"""Timestamp when the resource was created"""

    created_by: Annotated[OptionalNullable[str], pydantic.Field(alias="createdBy")] = (
        UNSET
    )
    r"""User who created the resource"""

    updated_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="updatedAt")
    ] = UNSET
    r"""Timestamp when the resource was last updated"""

    updated_by: Annotated[OptionalNullable[str], pydantic.Field(alias="updatedBy")] = (
        UNSET
    )
    r"""User who last updated the resource"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdAt", "createdBy", "updatedAt", "updatedBy"])
        nullable_fields = set(["createdAt", "createdBy", "updatedAt", "updatedBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchEqualsExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: NotRequired[Nullable[str]]
    r"""The ID of the external source"""
    source: NotRequired[Nullable[str]]
    r"""The source of the external information"""


class UnitSearchEqualsExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: Annotated[OptionalNullable[str], pydantic.Field(alias="sourceID")] = (
        UNSET
    )
    r"""The ID of the external source"""

    source: OptionalNullable[str] = UNSET
    r"""The source of the external information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sourceID", "source"])
        nullable_fields = set(["sourceID", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchEqualsTypedDict(TypedDict):
    r"""Equality filters for Unit"""

    id: NotRequired[Nullable[str]]
    r"""Unique identifier for the Unit"""
    meta: NotRequired[Nullable[UnitSearchEqualsMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitSearchEqualsExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""
    title: NotRequired[Nullable[str]]
    r"""The title of the unit"""
    description: NotRequired[Nullable[str]]
    r"""The description of the unit"""


class UnitSearchEquals(BaseModel):
    r"""Equality filters for Unit"""

    id: OptionalNullable[str] = UNSET
    r"""Unique identifier for the Unit"""

    meta: OptionalNullable[UnitSearchEqualsMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitSearchEqualsExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    title: OptionalNullable[str] = UNSET
    r"""The title of the unit"""

    description: OptionalNullable[str] = UNSET
    r"""The description of the unit"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "meta", "external", "title", "description"])
        nullable_fields = set(["id", "meta", "external", "title", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchNotEqualsMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""

    created_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was created"""
    created_by: NotRequired[Nullable[str]]
    r"""User who created the resource"""
    updated_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was last updated"""
    updated_by: NotRequired[Nullable[str]]
    r"""User who last updated the resource"""


class UnitSearchNotEqualsMeta(BaseModel):
    r"""Metadata information for the Unit"""

    created_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="createdAt")
    ] = UNSET
    r"""Timestamp when the resource was created"""

    created_by: Annotated[OptionalNullable[str], pydantic.Field(alias="createdBy")] = (
        UNSET
    )
    r"""User who created the resource"""

    updated_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="updatedAt")
    ] = UNSET
    r"""Timestamp when the resource was last updated"""

    updated_by: Annotated[OptionalNullable[str], pydantic.Field(alias="updatedBy")] = (
        UNSET
    )
    r"""User who last updated the resource"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdAt", "createdBy", "updatedAt", "updatedBy"])
        nullable_fields = set(["createdAt", "createdBy", "updatedAt", "updatedBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchNotEqualsExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: NotRequired[Nullable[str]]
    r"""The ID of the external source"""
    source: NotRequired[Nullable[str]]
    r"""The source of the external information"""


class UnitSearchNotEqualsExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: Annotated[OptionalNullable[str], pydantic.Field(alias="sourceID")] = (
        UNSET
    )
    r"""The ID of the external source"""

    source: OptionalNullable[str] = UNSET
    r"""The source of the external information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sourceID", "source"])
        nullable_fields = set(["sourceID", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchNotEqualsTypedDict(TypedDict):
    r"""Inequality filters for Unit"""

    id: NotRequired[Nullable[str]]
    r"""Unique identifier for the Unit"""
    meta: NotRequired[Nullable[UnitSearchNotEqualsMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitSearchNotEqualsExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""
    title: NotRequired[Nullable[str]]
    r"""The title of the unit"""
    description: NotRequired[Nullable[str]]
    r"""The description of the unit"""


class UnitSearchNotEquals(BaseModel):
    r"""Inequality filters for Unit"""

    id: OptionalNullable[str] = UNSET
    r"""Unique identifier for the Unit"""

    meta: OptionalNullable[UnitSearchNotEqualsMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitSearchNotEqualsExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    title: OptionalNullable[str] = UNSET
    r"""The title of the unit"""

    description: OptionalNullable[str] = UNSET
    r"""The description of the unit"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "meta", "external", "title", "description"])
        nullable_fields = set(["id", "meta", "external", "title", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchGreaterThanMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""

    created_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was created"""
    updated_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was last updated"""


class UnitSearchGreaterThanMeta(BaseModel):
    r"""Metadata information for the Unit"""

    created_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="createdAt")
    ] = UNSET
    r"""Timestamp when the resource was created"""

    updated_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="updatedAt")
    ] = UNSET
    r"""Timestamp when the resource was last updated"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdAt", "updatedAt"])
        nullable_fields = set(["createdAt", "updatedAt"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchGreaterThanExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitSearchGreaterThanExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitSearchGreaterThanTypedDict(TypedDict):
    r"""Greater than filters for Unit"""

    meta: NotRequired[Nullable[UnitSearchGreaterThanMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitSearchGreaterThanExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitSearchGreaterThan(BaseModel):
    r"""Greater than filters for Unit"""

    meta: OptionalNullable[UnitSearchGreaterThanMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitSearchGreaterThanExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["meta", "external"])
        nullable_fields = set(["meta", "external"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchSmallerThanMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""

    created_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was created"""
    updated_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was last updated"""


class UnitSearchSmallerThanMeta(BaseModel):
    r"""Metadata information for the Unit"""

    created_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="createdAt")
    ] = UNSET
    r"""Timestamp when the resource was created"""

    updated_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="updatedAt")
    ] = UNSET
    r"""Timestamp when the resource was last updated"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdAt", "updatedAt"])
        nullable_fields = set(["createdAt", "updatedAt"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchSmallerThanExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitSearchSmallerThanExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitSearchSmallerThanTypedDict(TypedDict):
    r"""Smaller than filters for Unit"""

    meta: NotRequired[Nullable[UnitSearchSmallerThanMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitSearchSmallerThanExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitSearchSmallerThan(BaseModel):
    r"""Smaller than filters for Unit"""

    meta: OptionalNullable[UnitSearchSmallerThanMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitSearchSmallerThanExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["meta", "external"])
        nullable_fields = set(["meta", "external"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchGreaterOrEqualMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""

    created_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was created"""
    updated_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was last updated"""


class UnitSearchGreaterOrEqualMeta(BaseModel):
    r"""Metadata information for the Unit"""

    created_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="createdAt")
    ] = UNSET
    r"""Timestamp when the resource was created"""

    updated_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="updatedAt")
    ] = UNSET
    r"""Timestamp when the resource was last updated"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdAt", "updatedAt"])
        nullable_fields = set(["createdAt", "updatedAt"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchGreaterOrEqualExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitSearchGreaterOrEqualExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitSearchGreaterOrEqualTypedDict(TypedDict):
    r"""Greater than or equal filters for Unit"""

    meta: NotRequired[Nullable[UnitSearchGreaterOrEqualMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitSearchGreaterOrEqualExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitSearchGreaterOrEqual(BaseModel):
    r"""Greater than or equal filters for Unit"""

    meta: OptionalNullable[UnitSearchGreaterOrEqualMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitSearchGreaterOrEqualExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["meta", "external"])
        nullable_fields = set(["meta", "external"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchSmallerOrEqualMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""

    created_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was created"""
    updated_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was last updated"""


class UnitSearchSmallerOrEqualMeta(BaseModel):
    r"""Metadata information for the Unit"""

    created_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="createdAt")
    ] = UNSET
    r"""Timestamp when the resource was created"""

    updated_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="updatedAt")
    ] = UNSET
    r"""Timestamp when the resource was last updated"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdAt", "updatedAt"])
        nullable_fields = set(["createdAt", "updatedAt"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchSmallerOrEqualExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitSearchSmallerOrEqualExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitSearchSmallerOrEqualTypedDict(TypedDict):
    r"""Smaller than or equal filters for Unit"""

    meta: NotRequired[Nullable[UnitSearchSmallerOrEqualMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitSearchSmallerOrEqualExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitSearchSmallerOrEqual(BaseModel):
    r"""Smaller than or equal filters for Unit"""

    meta: OptionalNullable[UnitSearchSmallerOrEqualMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitSearchSmallerOrEqualExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["meta", "external"])
        nullable_fields = set(["meta", "external"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchContainsMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""

    created_by: NotRequired[List[str]]
    r"""User who created the resource"""
    updated_by: NotRequired[List[str]]
    r"""User who last updated the resource"""


class UnitSearchContainsMeta(BaseModel):
    r"""Metadata information for the Unit"""

    created_by: Annotated[Optional[List[str]], pydantic.Field(alias="createdBy")] = None
    r"""User who created the resource"""

    updated_by: Annotated[Optional[List[str]], pydantic.Field(alias="updatedBy")] = None
    r"""User who last updated the resource"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdBy", "updatedBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UnitSearchContainsExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: NotRequired[List[str]]
    r"""The ID of the external source"""
    source: NotRequired[List[str]]
    r"""The source of the external information"""


class UnitSearchContainsExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: Annotated[Optional[List[str]], pydantic.Field(alias="sourceID")] = None
    r"""The ID of the external source"""

    source: Optional[List[str]] = None
    r"""The source of the external information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sourceID", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UnitSearchContainsTypedDict(TypedDict):
    r"""Contains filters for Unit"""

    id: NotRequired[List[str]]
    r"""Unique identifier for the Unit"""
    meta: NotRequired[Nullable[UnitSearchContainsMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitSearchContainsExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""
    title: NotRequired[List[str]]
    r"""The title of the unit"""
    description: NotRequired[List[str]]
    r"""The description of the unit"""


class UnitSearchContains(BaseModel):
    r"""Contains filters for Unit"""

    id: Optional[List[str]] = None
    r"""Unique identifier for the Unit"""

    meta: OptionalNullable[UnitSearchContainsMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitSearchContainsExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    title: Optional[List[str]] = None
    r"""The title of the unit"""

    description: Optional[List[str]] = None
    r"""The description of the unit"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "meta", "external", "title", "description"])
        nullable_fields = set(["meta", "external"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchNotContainsMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""

    created_by: NotRequired[List[str]]
    r"""User who created the resource"""
    updated_by: NotRequired[List[str]]
    r"""User who last updated the resource"""


class UnitSearchNotContainsMeta(BaseModel):
    r"""Metadata information for the Unit"""

    created_by: Annotated[Optional[List[str]], pydantic.Field(alias="createdBy")] = None
    r"""User who created the resource"""

    updated_by: Annotated[Optional[List[str]], pydantic.Field(alias="updatedBy")] = None
    r"""User who last updated the resource"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdBy", "updatedBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UnitSearchNotContainsExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: NotRequired[List[str]]
    r"""The ID of the external source"""
    source: NotRequired[List[str]]
    r"""The source of the external information"""


class UnitSearchNotContainsExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: Annotated[Optional[List[str]], pydantic.Field(alias="sourceID")] = None
    r"""The ID of the external source"""

    source: Optional[List[str]] = None
    r"""The source of the external information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sourceID", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UnitSearchNotContainsTypedDict(TypedDict):
    r"""Not contains filters for Unit"""

    id: NotRequired[List[str]]
    r"""Unique identifier for the Unit"""
    meta: NotRequired[Nullable[UnitSearchNotContainsMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitSearchNotContainsExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""
    title: NotRequired[List[str]]
    r"""The title of the unit"""
    description: NotRequired[List[str]]
    r"""The description of the unit"""


class UnitSearchNotContains(BaseModel):
    r"""Not contains filters for Unit"""

    id: Optional[List[str]] = None
    r"""Unique identifier for the Unit"""

    meta: OptionalNullable[UnitSearchNotContainsMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitSearchNotContainsExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    title: Optional[List[str]] = None
    r"""The title of the unit"""

    description: Optional[List[str]] = None
    r"""The description of the unit"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "meta", "external", "title", "description"])
        nullable_fields = set(["meta", "external"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchLikeMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""


class UnitSearchLikeMeta(BaseModel):
    r"""Metadata information for the Unit"""


class UnitSearchLikeExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: NotRequired[Nullable[str]]
    r"""The ID of the external source"""
    source: NotRequired[Nullable[str]]
    r"""The source of the external information"""


class UnitSearchLikeExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: Annotated[OptionalNullable[str], pydantic.Field(alias="sourceID")] = (
        UNSET
    )
    r"""The ID of the external source"""

    source: OptionalNullable[str] = UNSET
    r"""The source of the external information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sourceID", "source"])
        nullable_fields = set(["sourceID", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchLikeTypedDict(TypedDict):
    r"""LIKE filters for Unit"""

    meta: NotRequired[Nullable[UnitSearchLikeMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitSearchLikeExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""
    title: NotRequired[Nullable[str]]
    r"""The title of the unit"""
    description: NotRequired[Nullable[str]]
    r"""The description of the unit"""


class UnitSearchLike(BaseModel):
    r"""LIKE filters for Unit"""

    meta: OptionalNullable[UnitSearchLikeMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitSearchLikeExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    title: OptionalNullable[str] = UNSET
    r"""The title of the unit"""

    description: OptionalNullable[str] = UNSET
    r"""The description of the unit"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["meta", "external", "title", "description"])
        nullable_fields = set(["meta", "external", "title", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchNotLikeMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""


class UnitSearchNotLikeMeta(BaseModel):
    r"""Metadata information for the Unit"""


class UnitSearchNotLikeExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: NotRequired[Nullable[str]]
    r"""The ID of the external source"""
    source: NotRequired[Nullable[str]]
    r"""The source of the external information"""


class UnitSearchNotLikeExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: Annotated[OptionalNullable[str], pydantic.Field(alias="sourceID")] = (
        UNSET
    )
    r"""The ID of the external source"""

    source: OptionalNullable[str] = UNSET
    r"""The source of the external information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sourceID", "source"])
        nullable_fields = set(["sourceID", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchNotLikeTypedDict(TypedDict):
    r"""NOT LIKE filters for Unit"""

    meta: NotRequired[Nullable[UnitSearchNotLikeMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitSearchNotLikeExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""
    title: NotRequired[Nullable[str]]
    r"""The title of the unit"""
    description: NotRequired[Nullable[str]]
    r"""The description of the unit"""


class UnitSearchNotLike(BaseModel):
    r"""NOT LIKE filters for Unit"""

    meta: OptionalNullable[UnitSearchNotLikeMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitSearchNotLikeExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    title: OptionalNullable[str] = UNSET
    r"""The title of the unit"""

    description: OptionalNullable[str] = UNSET
    r"""The description of the unit"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["meta", "external", "title", "description"])
        nullable_fields = set(["meta", "external", "title", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchNullMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""

    created_by: NotRequired[Nullable[bool]]
    r"""User who created the resource"""
    updated_at: NotRequired[Nullable[bool]]
    r"""Timestamp when the resource was last updated"""
    updated_by: NotRequired[Nullable[bool]]
    r"""User who last updated the resource"""


class UnitSearchNullMeta(BaseModel):
    r"""Metadata information for the Unit"""

    created_by: Annotated[OptionalNullable[bool], pydantic.Field(alias="createdBy")] = (
        UNSET
    )
    r"""User who created the resource"""

    updated_at: Annotated[OptionalNullable[bool], pydantic.Field(alias="updatedAt")] = (
        UNSET
    )
    r"""Timestamp when the resource was last updated"""

    updated_by: Annotated[OptionalNullable[bool], pydantic.Field(alias="updatedBy")] = (
        UNSET
    )
    r"""User who last updated the resource"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdBy", "updatedAt", "updatedBy"])
        nullable_fields = set(["createdBy", "updatedAt", "updatedBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchNullExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: NotRequired[Nullable[bool]]
    r"""The ID of the external source"""
    source: NotRequired[Nullable[bool]]
    r"""The source of the external information"""


class UnitSearchNullExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: Annotated[OptionalNullable[bool], pydantic.Field(alias="sourceID")] = (
        UNSET
    )
    r"""The ID of the external source"""

    source: OptionalNullable[bool] = UNSET
    r"""The source of the external information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sourceID", "source"])
        nullable_fields = set(["sourceID", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchNullTypedDict(TypedDict):
    r"""Null filters for Unit"""

    meta: NotRequired[Nullable[UnitSearchNullMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitSearchNullExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""
    description: NotRequired[Nullable[bool]]
    r"""The description of the unit"""


class UnitSearchNull(BaseModel):
    r"""Null filters for Unit"""

    meta: OptionalNullable[UnitSearchNullMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitSearchNullExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    description: OptionalNullable[bool] = UNSET
    r"""The description of the unit"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["meta", "external", "description"])
        nullable_fields = set(["meta", "external", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchNotNullMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""

    created_by: NotRequired[Nullable[bool]]
    r"""User who created the resource"""
    updated_at: NotRequired[Nullable[bool]]
    r"""Timestamp when the resource was last updated"""
    updated_by: NotRequired[Nullable[bool]]
    r"""User who last updated the resource"""


class UnitSearchNotNullMeta(BaseModel):
    r"""Metadata information for the Unit"""

    created_by: Annotated[OptionalNullable[bool], pydantic.Field(alias="createdBy")] = (
        UNSET
    )
    r"""User who created the resource"""

    updated_at: Annotated[OptionalNullable[bool], pydantic.Field(alias="updatedAt")] = (
        UNSET
    )
    r"""Timestamp when the resource was last updated"""

    updated_by: Annotated[OptionalNullable[bool], pydantic.Field(alias="updatedBy")] = (
        UNSET
    )
    r"""User who last updated the resource"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdBy", "updatedAt", "updatedBy"])
        nullable_fields = set(["createdBy", "updatedAt", "updatedBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchNotNullExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: NotRequired[Nullable[bool]]
    r"""The ID of the external source"""
    source: NotRequired[Nullable[bool]]
    r"""The source of the external information"""


class UnitSearchNotNullExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: Annotated[OptionalNullable[bool], pydantic.Field(alias="sourceID")] = (
        UNSET
    )
    r"""The ID of the external source"""

    source: OptionalNullable[bool] = UNSET
    r"""The source of the external information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sourceID", "source"])
        nullable_fields = set(["sourceID", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchNotNullTypedDict(TypedDict):
    r"""Not null filters for Unit"""

    meta: NotRequired[Nullable[UnitSearchNotNullMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitSearchNotNullExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""
    description: NotRequired[Nullable[bool]]
    r"""The description of the unit"""


class UnitSearchNotNull(BaseModel):
    r"""Not null filters for Unit"""

    meta: OptionalNullable[UnitSearchNotNullMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitSearchNotNullExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    description: OptionalNullable[bool] = UNSET
    r"""The description of the unit"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["meta", "external", "description"])
        nullable_fields = set(["meta", "external", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchFilterTypedDict(TypedDict):
    r"""Filter criteria to search for specific records"""

    or_condition: bool
    r"""OrCondition decides if this filter is within an OR-condition or AND-condition"""
    equals: NotRequired[Nullable[UnitSearchEqualsTypedDict]]
    r"""Equality filters for Unit"""
    not_equals: NotRequired[Nullable[UnitSearchNotEqualsTypedDict]]
    r"""Inequality filters for Unit"""
    greater_than: NotRequired[Nullable[UnitSearchGreaterThanTypedDict]]
    r"""Greater than filters for Unit"""
    smaller_than: NotRequired[Nullable[UnitSearchSmallerThanTypedDict]]
    r"""Smaller than filters for Unit"""
    greater_or_equal: NotRequired[Nullable[UnitSearchGreaterOrEqualTypedDict]]
    r"""Greater than or equal filters for Unit"""
    smaller_or_equal: NotRequired[Nullable[UnitSearchSmallerOrEqualTypedDict]]
    r"""Smaller than or equal filters for Unit"""
    contains: NotRequired[Nullable[UnitSearchContainsTypedDict]]
    r"""Contains filters for Unit"""
    not_contains: NotRequired[Nullable[UnitSearchNotContainsTypedDict]]
    r"""Not contains filters for Unit"""
    like: NotRequired[Nullable[UnitSearchLikeTypedDict]]
    r"""LIKE filters for Unit"""
    not_like: NotRequired[Nullable[UnitSearchNotLikeTypedDict]]
    r"""NOT LIKE filters for Unit"""
    null: NotRequired[Nullable[UnitSearchNullTypedDict]]
    r"""Null filters for Unit"""
    not_null: NotRequired[Nullable[UnitSearchNotNullTypedDict]]
    r"""Not null filters for Unit"""
    nested_filters: NotRequired[List[UnitFilterTypedDict]]
    r"""NestedFilters of the Unit, useful for more complex filters"""


class UnitSearchFilter(BaseModel):
    r"""Filter criteria to search for specific records"""

    or_condition: Annotated[bool, pydantic.Field(alias="orCondition")]
    r"""OrCondition decides if this filter is within an OR-condition or AND-condition"""

    equals: OptionalNullable[UnitSearchEquals] = UNSET
    r"""Equality filters for Unit"""

    not_equals: Annotated[
        OptionalNullable[UnitSearchNotEquals], pydantic.Field(alias="notEquals")
    ] = UNSET
    r"""Inequality filters for Unit"""

    greater_than: Annotated[
        OptionalNullable[UnitSearchGreaterThan], pydantic.Field(alias="greaterThan")
    ] = UNSET
    r"""Greater than filters for Unit"""

    smaller_than: Annotated[
        OptionalNullable[UnitSearchSmallerThan], pydantic.Field(alias="smallerThan")
    ] = UNSET
    r"""Smaller than filters for Unit"""

    greater_or_equal: Annotated[
        OptionalNullable[UnitSearchGreaterOrEqual],
        pydantic.Field(alias="greaterOrEqual"),
    ] = UNSET
    r"""Greater than or equal filters for Unit"""

    smaller_or_equal: Annotated[
        OptionalNullable[UnitSearchSmallerOrEqual],
        pydantic.Field(alias="smallerOrEqual"),
    ] = UNSET
    r"""Smaller than or equal filters for Unit"""

    contains: OptionalNullable[UnitSearchContains] = UNSET
    r"""Contains filters for Unit"""

    not_contains: Annotated[
        OptionalNullable[UnitSearchNotContains], pydantic.Field(alias="notContains")
    ] = UNSET
    r"""Not contains filters for Unit"""

    like: OptionalNullable[UnitSearchLike] = UNSET
    r"""LIKE filters for Unit"""

    not_like: Annotated[
        OptionalNullable[UnitSearchNotLike], pydantic.Field(alias="notLike")
    ] = UNSET
    r"""NOT LIKE filters for Unit"""

    null: OptionalNullable[UnitSearchNull] = UNSET
    r"""Null filters for Unit"""

    not_null: Annotated[
        OptionalNullable[UnitSearchNotNull], pydantic.Field(alias="notNull")
    ] = UNSET
    r"""Not null filters for Unit"""

    nested_filters: Annotated[
        Optional[List[UnitFilter]], pydantic.Field(alias="nestedFilters")
    ] = None
    r"""NestedFilters of the Unit, useful for more complex filters"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "equals",
                "notEquals",
                "greaterThan",
                "smallerThan",
                "greaterOrEqual",
                "smallerOrEqual",
                "contains",
                "notContains",
                "like",
                "notLike",
                "null",
                "notNull",
                "nestedFilters",
            ]
        )
        nullable_fields = set(
            [
                "equals",
                "notEquals",
                "greaterThan",
                "smallerThan",
                "greaterOrEqual",
                "smallerOrEqual",
                "contains",
                "notContains",
                "like",
                "notLike",
                "null",
                "notNull",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitSearchRequestBodyTypedDict(TypedDict):
    r"""Request body"""

    filter_: UnitSearchFilterTypedDict
    r"""Filter criteria to search for specific records"""


class UnitSearchRequestBody(BaseModel):
    r"""Request body"""

    filter_: Annotated[UnitSearchFilter, pydantic.Field(alias="filter")]
    r"""Filter criteria to search for specific records"""


try:
    UnitSearchEqualsMeta.model_rebuild()
except NameError:
    pass
try:
    UnitSearchEqualsExternal.model_rebuild()
except NameError:
    pass
try:
    UnitSearchNotEqualsMeta.model_rebuild()
except NameError:
    pass
try:
    UnitSearchNotEqualsExternal.model_rebuild()
except NameError:
    pass
try:
    UnitSearchGreaterThanMeta.model_rebuild()
except NameError:
    pass
try:
    UnitSearchSmallerThanMeta.model_rebuild()
except NameError:
    pass
try:
    UnitSearchGreaterOrEqualMeta.model_rebuild()
except NameError:
    pass
try:
    UnitSearchSmallerOrEqualMeta.model_rebuild()
except NameError:
    pass
try:
    UnitSearchContainsMeta.model_rebuild()
except NameError:
    pass
try:
    UnitSearchContainsExternal.model_rebuild()
except NameError:
    pass
try:
    UnitSearchNotContainsMeta.model_rebuild()
except NameError:
    pass
try:
    UnitSearchNotContainsExternal.model_rebuild()
except NameError:
    pass
try:
    UnitSearchLikeExternal.model_rebuild()
except NameError:
    pass
try:
    UnitSearchNotLikeExternal.model_rebuild()
except NameError:
    pass
try:
    UnitSearchNullMeta.model_rebuild()
except NameError:
    pass
try:
    UnitSearchNullExternal.model_rebuild()
except NameError:
    pass
try:
    UnitSearchNotNullMeta.model_rebuild()
except NameError:
    pass
try:
    UnitSearchNotNullExternal.model_rebuild()
except NameError:
    pass
try:
    UnitSearchFilter.model_rebuild()
except NameError:
    pass
try:
    UnitSearchRequestBody.model_rebuild()
except NameError:
    pass
