"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .unitsearch_requestbody import (
    UnitSearchRequestBody,
    UnitSearchRequestBodyTypedDict,
)
from .unitsearch_response import UnitSearchResponse, UnitSearchResponseTypedDict
from meitner.types import BaseModel, UNSET_SENTINEL
from meitner.utils import FieldMetadata, QueryParamMetadata, RequestMetadata
from pydantic import model_serializer
from typing import Awaitable, Callable, Dict, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class UnitSearchRequestTypedDict(TypedDict):
    unit_search: UnitSearchRequestBodyTypedDict
    r"""Request body"""
    limit: NotRequired[int]
    r"""The maximum number of Units to return (default: 50) when searching Units"""
    offset: NotRequired[int]
    r"""The number of Units to skip before starting to return results (default: 0) when searching Units"""


class UnitSearchRequest(BaseModel):
    unit_search: Annotated[
        UnitSearchRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Request body"""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 50
    r"""The maximum number of Units to return (default: 50) when searching Units"""

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0
    r"""The number of Units to skip before starting to return results (default: 0) when searching Units"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["limit", "offset"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UnitSearchResponseResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: UnitSearchResponseTypedDict


class UnitSearchResponseResponse(BaseModel):
    next: Union[
        Callable[[], Optional[UnitSearchResponseResponse]],
        Callable[[], Awaitable[Optional[UnitSearchResponseResponse]]],
    ]

    headers: Dict[str, List[str]]

    result: UnitSearchResponse
