"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .unit import Unit, UnitTypedDict
from meitner.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class UnitSearchPaginationTypedDict(TypedDict):
    r"""Pagination information"""

    offset: int
    r"""Number of items to skip from the beginning of the result set"""
    limit: int
    r"""Maximum number of items to return in the result set"""
    total: int
    r"""Total number of items available for pagination"""


class UnitSearchPagination(BaseModel):
    r"""Pagination information"""

    offset: int
    r"""Number of items to skip from the beginning of the result set"""

    limit: int
    r"""Maximum number of items to return in the result set"""

    total: int
    r"""Total number of items available for pagination"""


class UnitSearchResponseTypedDict(TypedDict):
    r"""Response for Unit Search operation - returns filtered Unit results"""

    data: NotRequired[List[UnitTypedDict]]
    r"""Array of Unit objects"""
    pagination: NotRequired[UnitSearchPaginationTypedDict]
    r"""Pagination information"""


class UnitSearchResponse(BaseModel):
    r"""Response for Unit Search operation - returns filtered Unit results"""

    data: Optional[List[Unit]] = None
    r"""Array of Unit objects"""

    pagination: Optional[UnitSearchPagination] = None
    r"""Pagination information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data", "pagination"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
