"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from meitner.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UnitFilterEqualsMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""

    created_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was created"""
    created_by: NotRequired[Nullable[str]]
    r"""User who created the resource"""
    updated_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was last updated"""
    updated_by: NotRequired[Nullable[str]]
    r"""User who last updated the resource"""


class UnitFilterEqualsMeta(BaseModel):
    r"""Metadata information for the Unit"""

    created_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="createdAt")
    ] = UNSET
    r"""Timestamp when the resource was created"""

    created_by: Annotated[OptionalNullable[str], pydantic.Field(alias="createdBy")] = (
        UNSET
    )
    r"""User who created the resource"""

    updated_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="updatedAt")
    ] = UNSET
    r"""Timestamp when the resource was last updated"""

    updated_by: Annotated[OptionalNullable[str], pydantic.Field(alias="updatedBy")] = (
        UNSET
    )
    r"""User who last updated the resource"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdAt", "createdBy", "updatedAt", "updatedBy"])
        nullable_fields = set(["createdAt", "createdBy", "updatedAt", "updatedBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterEqualsExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: NotRequired[Nullable[str]]
    r"""The ID of the external source"""
    source: NotRequired[Nullable[str]]
    r"""The source of the external information"""


class UnitFilterEqualsExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: Annotated[OptionalNullable[str], pydantic.Field(alias="sourceID")] = (
        UNSET
    )
    r"""The ID of the external source"""

    source: OptionalNullable[str] = UNSET
    r"""The source of the external information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sourceID", "source"])
        nullable_fields = set(["sourceID", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterEqualsTypedDict(TypedDict):
    r"""Equality filters for Unit"""

    id: NotRequired[Nullable[str]]
    r"""Unique identifier for the Unit"""
    meta: NotRequired[Nullable[UnitFilterEqualsMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitFilterEqualsExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""
    title: NotRequired[Nullable[str]]
    r"""The title of the unit"""
    description: NotRequired[Nullable[str]]
    r"""The description of the unit"""


class UnitFilterEquals(BaseModel):
    r"""Equality filters for Unit"""

    id: OptionalNullable[str] = UNSET
    r"""Unique identifier for the Unit"""

    meta: OptionalNullable[UnitFilterEqualsMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitFilterEqualsExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    title: OptionalNullable[str] = UNSET
    r"""The title of the unit"""

    description: OptionalNullable[str] = UNSET
    r"""The description of the unit"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "meta", "external", "title", "description"])
        nullable_fields = set(["id", "meta", "external", "title", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterNotEqualsMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""

    created_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was created"""
    created_by: NotRequired[Nullable[str]]
    r"""User who created the resource"""
    updated_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was last updated"""
    updated_by: NotRequired[Nullable[str]]
    r"""User who last updated the resource"""


class UnitFilterNotEqualsMeta(BaseModel):
    r"""Metadata information for the Unit"""

    created_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="createdAt")
    ] = UNSET
    r"""Timestamp when the resource was created"""

    created_by: Annotated[OptionalNullable[str], pydantic.Field(alias="createdBy")] = (
        UNSET
    )
    r"""User who created the resource"""

    updated_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="updatedAt")
    ] = UNSET
    r"""Timestamp when the resource was last updated"""

    updated_by: Annotated[OptionalNullable[str], pydantic.Field(alias="updatedBy")] = (
        UNSET
    )
    r"""User who last updated the resource"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdAt", "createdBy", "updatedAt", "updatedBy"])
        nullable_fields = set(["createdAt", "createdBy", "updatedAt", "updatedBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterNotEqualsExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: NotRequired[Nullable[str]]
    r"""The ID of the external source"""
    source: NotRequired[Nullable[str]]
    r"""The source of the external information"""


class UnitFilterNotEqualsExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: Annotated[OptionalNullable[str], pydantic.Field(alias="sourceID")] = (
        UNSET
    )
    r"""The ID of the external source"""

    source: OptionalNullable[str] = UNSET
    r"""The source of the external information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sourceID", "source"])
        nullable_fields = set(["sourceID", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterNotEqualsTypedDict(TypedDict):
    r"""Inequality filters for Unit"""

    id: NotRequired[Nullable[str]]
    r"""Unique identifier for the Unit"""
    meta: NotRequired[Nullable[UnitFilterNotEqualsMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitFilterNotEqualsExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""
    title: NotRequired[Nullable[str]]
    r"""The title of the unit"""
    description: NotRequired[Nullable[str]]
    r"""The description of the unit"""


class UnitFilterNotEquals(BaseModel):
    r"""Inequality filters for Unit"""

    id: OptionalNullable[str] = UNSET
    r"""Unique identifier for the Unit"""

    meta: OptionalNullable[UnitFilterNotEqualsMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitFilterNotEqualsExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    title: OptionalNullable[str] = UNSET
    r"""The title of the unit"""

    description: OptionalNullable[str] = UNSET
    r"""The description of the unit"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "meta", "external", "title", "description"])
        nullable_fields = set(["id", "meta", "external", "title", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterGreaterThanMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""

    created_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was created"""
    updated_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was last updated"""


class UnitFilterGreaterThanMeta(BaseModel):
    r"""Metadata information for the Unit"""

    created_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="createdAt")
    ] = UNSET
    r"""Timestamp when the resource was created"""

    updated_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="updatedAt")
    ] = UNSET
    r"""Timestamp when the resource was last updated"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdAt", "updatedAt"])
        nullable_fields = set(["createdAt", "updatedAt"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterGreaterThanExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitFilterGreaterThanExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitFilterGreaterThanTypedDict(TypedDict):
    r"""Greater than filters for Unit"""

    meta: NotRequired[Nullable[UnitFilterGreaterThanMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitFilterGreaterThanExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitFilterGreaterThan(BaseModel):
    r"""Greater than filters for Unit"""

    meta: OptionalNullable[UnitFilterGreaterThanMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitFilterGreaterThanExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["meta", "external"])
        nullable_fields = set(["meta", "external"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterSmallerThanMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""

    created_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was created"""
    updated_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was last updated"""


class UnitFilterSmallerThanMeta(BaseModel):
    r"""Metadata information for the Unit"""

    created_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="createdAt")
    ] = UNSET
    r"""Timestamp when the resource was created"""

    updated_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="updatedAt")
    ] = UNSET
    r"""Timestamp when the resource was last updated"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdAt", "updatedAt"])
        nullable_fields = set(["createdAt", "updatedAt"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterSmallerThanExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitFilterSmallerThanExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitFilterSmallerThanTypedDict(TypedDict):
    r"""Smaller than filters for Unit"""

    meta: NotRequired[Nullable[UnitFilterSmallerThanMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitFilterSmallerThanExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitFilterSmallerThan(BaseModel):
    r"""Smaller than filters for Unit"""

    meta: OptionalNullable[UnitFilterSmallerThanMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitFilterSmallerThanExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["meta", "external"])
        nullable_fields = set(["meta", "external"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterGreaterOrEqualMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""

    created_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was created"""
    updated_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was last updated"""


class UnitFilterGreaterOrEqualMeta(BaseModel):
    r"""Metadata information for the Unit"""

    created_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="createdAt")
    ] = UNSET
    r"""Timestamp when the resource was created"""

    updated_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="updatedAt")
    ] = UNSET
    r"""Timestamp when the resource was last updated"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdAt", "updatedAt"])
        nullable_fields = set(["createdAt", "updatedAt"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterGreaterOrEqualExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitFilterGreaterOrEqualExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitFilterGreaterOrEqualTypedDict(TypedDict):
    r"""Greater than or equal filters for Unit"""

    meta: NotRequired[Nullable[UnitFilterGreaterOrEqualMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitFilterGreaterOrEqualExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitFilterGreaterOrEqual(BaseModel):
    r"""Greater than or equal filters for Unit"""

    meta: OptionalNullable[UnitFilterGreaterOrEqualMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitFilterGreaterOrEqualExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["meta", "external"])
        nullable_fields = set(["meta", "external"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterSmallerOrEqualMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""

    created_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was created"""
    updated_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the resource was last updated"""


class UnitFilterSmallerOrEqualMeta(BaseModel):
    r"""Metadata information for the Unit"""

    created_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="createdAt")
    ] = UNSET
    r"""Timestamp when the resource was created"""

    updated_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="updatedAt")
    ] = UNSET
    r"""Timestamp when the resource was last updated"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdAt", "updatedAt"])
        nullable_fields = set(["createdAt", "updatedAt"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterSmallerOrEqualExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitFilterSmallerOrEqualExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitFilterSmallerOrEqualTypedDict(TypedDict):
    r"""Smaller than or equal filters for Unit"""

    meta: NotRequired[Nullable[UnitFilterSmallerOrEqualMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitFilterSmallerOrEqualExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""


class UnitFilterSmallerOrEqual(BaseModel):
    r"""Smaller than or equal filters for Unit"""

    meta: OptionalNullable[UnitFilterSmallerOrEqualMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitFilterSmallerOrEqualExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["meta", "external"])
        nullable_fields = set(["meta", "external"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterContainsMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""

    created_by: NotRequired[List[str]]
    r"""User who created the resource"""
    updated_by: NotRequired[List[str]]
    r"""User who last updated the resource"""


class UnitFilterContainsMeta(BaseModel):
    r"""Metadata information for the Unit"""

    created_by: Annotated[Optional[List[str]], pydantic.Field(alias="createdBy")] = None
    r"""User who created the resource"""

    updated_by: Annotated[Optional[List[str]], pydantic.Field(alias="updatedBy")] = None
    r"""User who last updated the resource"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdBy", "updatedBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UnitFilterContainsExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: NotRequired[List[str]]
    r"""The ID of the external source"""
    source: NotRequired[List[str]]
    r"""The source of the external information"""


class UnitFilterContainsExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: Annotated[Optional[List[str]], pydantic.Field(alias="sourceID")] = None
    r"""The ID of the external source"""

    source: Optional[List[str]] = None
    r"""The source of the external information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sourceID", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UnitFilterContainsTypedDict(TypedDict):
    r"""Contains filters for Unit"""

    id: NotRequired[List[str]]
    r"""Unique identifier for the Unit"""
    meta: NotRequired[Nullable[UnitFilterContainsMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitFilterContainsExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""
    title: NotRequired[List[str]]
    r"""The title of the unit"""
    description: NotRequired[List[str]]
    r"""The description of the unit"""


class UnitFilterContains(BaseModel):
    r"""Contains filters for Unit"""

    id: Optional[List[str]] = None
    r"""Unique identifier for the Unit"""

    meta: OptionalNullable[UnitFilterContainsMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitFilterContainsExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    title: Optional[List[str]] = None
    r"""The title of the unit"""

    description: Optional[List[str]] = None
    r"""The description of the unit"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "meta", "external", "title", "description"])
        nullable_fields = set(["meta", "external"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterNotContainsMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""

    created_by: NotRequired[List[str]]
    r"""User who created the resource"""
    updated_by: NotRequired[List[str]]
    r"""User who last updated the resource"""


class UnitFilterNotContainsMeta(BaseModel):
    r"""Metadata information for the Unit"""

    created_by: Annotated[Optional[List[str]], pydantic.Field(alias="createdBy")] = None
    r"""User who created the resource"""

    updated_by: Annotated[Optional[List[str]], pydantic.Field(alias="updatedBy")] = None
    r"""User who last updated the resource"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdBy", "updatedBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UnitFilterNotContainsExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: NotRequired[List[str]]
    r"""The ID of the external source"""
    source: NotRequired[List[str]]
    r"""The source of the external information"""


class UnitFilterNotContainsExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: Annotated[Optional[List[str]], pydantic.Field(alias="sourceID")] = None
    r"""The ID of the external source"""

    source: Optional[List[str]] = None
    r"""The source of the external information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sourceID", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UnitFilterNotContainsTypedDict(TypedDict):
    r"""Not contains filters for Unit"""

    id: NotRequired[List[str]]
    r"""Unique identifier for the Unit"""
    meta: NotRequired[Nullable[UnitFilterNotContainsMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitFilterNotContainsExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""
    title: NotRequired[List[str]]
    r"""The title of the unit"""
    description: NotRequired[List[str]]
    r"""The description of the unit"""


class UnitFilterNotContains(BaseModel):
    r"""Not contains filters for Unit"""

    id: Optional[List[str]] = None
    r"""Unique identifier for the Unit"""

    meta: OptionalNullable[UnitFilterNotContainsMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitFilterNotContainsExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    title: Optional[List[str]] = None
    r"""The title of the unit"""

    description: Optional[List[str]] = None
    r"""The description of the unit"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "meta", "external", "title", "description"])
        nullable_fields = set(["meta", "external"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterLikeMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""


class UnitFilterLikeMeta(BaseModel):
    r"""Metadata information for the Unit"""


class UnitFilterLikeExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: NotRequired[Nullable[str]]
    r"""The ID of the external source"""
    source: NotRequired[Nullable[str]]
    r"""The source of the external information"""


class UnitFilterLikeExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: Annotated[OptionalNullable[str], pydantic.Field(alias="sourceID")] = (
        UNSET
    )
    r"""The ID of the external source"""

    source: OptionalNullable[str] = UNSET
    r"""The source of the external information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sourceID", "source"])
        nullable_fields = set(["sourceID", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterLikeTypedDict(TypedDict):
    r"""LIKE filters for Unit"""

    meta: NotRequired[Nullable[UnitFilterLikeMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitFilterLikeExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""
    title: NotRequired[Nullable[str]]
    r"""The title of the unit"""
    description: NotRequired[Nullable[str]]
    r"""The description of the unit"""


class UnitFilterLike(BaseModel):
    r"""LIKE filters for Unit"""

    meta: OptionalNullable[UnitFilterLikeMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitFilterLikeExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    title: OptionalNullable[str] = UNSET
    r"""The title of the unit"""

    description: OptionalNullable[str] = UNSET
    r"""The description of the unit"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["meta", "external", "title", "description"])
        nullable_fields = set(["meta", "external", "title", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterNotLikeMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""


class UnitFilterNotLikeMeta(BaseModel):
    r"""Metadata information for the Unit"""


class UnitFilterNotLikeExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: NotRequired[Nullable[str]]
    r"""The ID of the external source"""
    source: NotRequired[Nullable[str]]
    r"""The source of the external information"""


class UnitFilterNotLikeExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: Annotated[OptionalNullable[str], pydantic.Field(alias="sourceID")] = (
        UNSET
    )
    r"""The ID of the external source"""

    source: OptionalNullable[str] = UNSET
    r"""The source of the external information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sourceID", "source"])
        nullable_fields = set(["sourceID", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterNotLikeTypedDict(TypedDict):
    r"""NOT LIKE filters for Unit"""

    meta: NotRequired[Nullable[UnitFilterNotLikeMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitFilterNotLikeExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""
    title: NotRequired[Nullable[str]]
    r"""The title of the unit"""
    description: NotRequired[Nullable[str]]
    r"""The description of the unit"""


class UnitFilterNotLike(BaseModel):
    r"""NOT LIKE filters for Unit"""

    meta: OptionalNullable[UnitFilterNotLikeMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitFilterNotLikeExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    title: OptionalNullable[str] = UNSET
    r"""The title of the unit"""

    description: OptionalNullable[str] = UNSET
    r"""The description of the unit"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["meta", "external", "title", "description"])
        nullable_fields = set(["meta", "external", "title", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterNullMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""

    created_by: NotRequired[Nullable[bool]]
    r"""User who created the resource"""
    updated_at: NotRequired[Nullable[bool]]
    r"""Timestamp when the resource was last updated"""
    updated_by: NotRequired[Nullable[bool]]
    r"""User who last updated the resource"""


class UnitFilterNullMeta(BaseModel):
    r"""Metadata information for the Unit"""

    created_by: Annotated[OptionalNullable[bool], pydantic.Field(alias="createdBy")] = (
        UNSET
    )
    r"""User who created the resource"""

    updated_at: Annotated[OptionalNullable[bool], pydantic.Field(alias="updatedAt")] = (
        UNSET
    )
    r"""Timestamp when the resource was last updated"""

    updated_by: Annotated[OptionalNullable[bool], pydantic.Field(alias="updatedBy")] = (
        UNSET
    )
    r"""User who last updated the resource"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdBy", "updatedAt", "updatedBy"])
        nullable_fields = set(["createdBy", "updatedAt", "updatedBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterNullExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: NotRequired[Nullable[bool]]
    r"""The ID of the external source"""
    source: NotRequired[Nullable[bool]]
    r"""The source of the external information"""


class UnitFilterNullExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: Annotated[OptionalNullable[bool], pydantic.Field(alias="sourceID")] = (
        UNSET
    )
    r"""The ID of the external source"""

    source: OptionalNullable[bool] = UNSET
    r"""The source of the external information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sourceID", "source"])
        nullable_fields = set(["sourceID", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterNullTypedDict(TypedDict):
    r"""Null filters for Unit"""

    meta: NotRequired[Nullable[UnitFilterNullMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitFilterNullExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""
    description: NotRequired[Nullable[bool]]
    r"""The description of the unit"""


class UnitFilterNull(BaseModel):
    r"""Null filters for Unit"""

    meta: OptionalNullable[UnitFilterNullMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitFilterNullExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    description: OptionalNullable[bool] = UNSET
    r"""The description of the unit"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["meta", "external", "description"])
        nullable_fields = set(["meta", "external", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterNotNullMetaTypedDict(TypedDict):
    r"""Metadata information for the Unit"""

    created_by: NotRequired[Nullable[bool]]
    r"""User who created the resource"""
    updated_at: NotRequired[Nullable[bool]]
    r"""Timestamp when the resource was last updated"""
    updated_by: NotRequired[Nullable[bool]]
    r"""User who last updated the resource"""


class UnitFilterNotNullMeta(BaseModel):
    r"""Metadata information for the Unit"""

    created_by: Annotated[OptionalNullable[bool], pydantic.Field(alias="createdBy")] = (
        UNSET
    )
    r"""User who created the resource"""

    updated_at: Annotated[OptionalNullable[bool], pydantic.Field(alias="updatedAt")] = (
        UNSET
    )
    r"""Timestamp when the resource was last updated"""

    updated_by: Annotated[OptionalNullable[bool], pydantic.Field(alias="updatedBy")] = (
        UNSET
    )
    r"""User who last updated the resource"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdBy", "updatedAt", "updatedBy"])
        nullable_fields = set(["createdBy", "updatedAt", "updatedBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterNotNullExternalTypedDict(TypedDict):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: NotRequired[Nullable[bool]]
    r"""The ID of the external source"""
    source: NotRequired[Nullable[bool]]
    r"""The source of the external information"""


class UnitFilterNotNullExternal(BaseModel):
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    source_id: Annotated[OptionalNullable[bool], pydantic.Field(alias="sourceID")] = (
        UNSET
    )
    r"""The ID of the external source"""

    source: OptionalNullable[bool] = UNSET
    r"""The source of the external information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sourceID", "source"])
        nullable_fields = set(["sourceID", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterNotNullTypedDict(TypedDict):
    r"""Not null filters for Unit"""

    meta: NotRequired[Nullable[UnitFilterNotNullMetaTypedDict]]
    r"""Metadata information for the Unit"""
    external: NotRequired[Nullable[UnitFilterNotNullExternalTypedDict]]
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""
    description: NotRequired[Nullable[bool]]
    r"""The description of the unit"""


class UnitFilterNotNull(BaseModel):
    r"""Not null filters for Unit"""

    meta: OptionalNullable[UnitFilterNotNullMeta] = UNSET
    r"""Metadata information for the Unit"""

    external: OptionalNullable[UnitFilterNotNullExternal] = UNSET
    r"""External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking."""

    description: OptionalNullable[bool] = UNSET
    r"""The description of the unit"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["meta", "external", "description"])
        nullable_fields = set(["meta", "external", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UnitFilterTypedDict(TypedDict):
    r"""Filter object for Unit"""

    or_condition: bool
    r"""OrCondition decides if this filter is within an OR-condition or AND-condition"""
    equals: NotRequired[Nullable[UnitFilterEqualsTypedDict]]
    r"""Equality filters for Unit"""
    not_equals: NotRequired[Nullable[UnitFilterNotEqualsTypedDict]]
    r"""Inequality filters for Unit"""
    greater_than: NotRequired[Nullable[UnitFilterGreaterThanTypedDict]]
    r"""Greater than filters for Unit"""
    smaller_than: NotRequired[Nullable[UnitFilterSmallerThanTypedDict]]
    r"""Smaller than filters for Unit"""
    greater_or_equal: NotRequired[Nullable[UnitFilterGreaterOrEqualTypedDict]]
    r"""Greater than or equal filters for Unit"""
    smaller_or_equal: NotRequired[Nullable[UnitFilterSmallerOrEqualTypedDict]]
    r"""Smaller than or equal filters for Unit"""
    contains: NotRequired[Nullable[UnitFilterContainsTypedDict]]
    r"""Contains filters for Unit"""
    not_contains: NotRequired[Nullable[UnitFilterNotContainsTypedDict]]
    r"""Not contains filters for Unit"""
    like: NotRequired[Nullable[UnitFilterLikeTypedDict]]
    r"""LIKE filters for Unit"""
    not_like: NotRequired[Nullable[UnitFilterNotLikeTypedDict]]
    r"""NOT LIKE filters for Unit"""
    null: NotRequired[Nullable[UnitFilterNullTypedDict]]
    r"""Null filters for Unit"""
    not_null: NotRequired[Nullable[UnitFilterNotNullTypedDict]]
    r"""Not null filters for Unit"""
    nested_filters: NotRequired[List[UnitFilterTypedDict]]
    r"""NestedFilters of the Unit, useful for more complex filters"""


class UnitFilter(BaseModel):
    r"""Filter object for Unit"""

    or_condition: Annotated[bool, pydantic.Field(alias="orCondition")]
    r"""OrCondition decides if this filter is within an OR-condition or AND-condition"""

    equals: OptionalNullable[UnitFilterEquals] = UNSET
    r"""Equality filters for Unit"""

    not_equals: Annotated[
        OptionalNullable[UnitFilterNotEquals], pydantic.Field(alias="notEquals")
    ] = UNSET
    r"""Inequality filters for Unit"""

    greater_than: Annotated[
        OptionalNullable[UnitFilterGreaterThan], pydantic.Field(alias="greaterThan")
    ] = UNSET
    r"""Greater than filters for Unit"""

    smaller_than: Annotated[
        OptionalNullable[UnitFilterSmallerThan], pydantic.Field(alias="smallerThan")
    ] = UNSET
    r"""Smaller than filters for Unit"""

    greater_or_equal: Annotated[
        OptionalNullable[UnitFilterGreaterOrEqual],
        pydantic.Field(alias="greaterOrEqual"),
    ] = UNSET
    r"""Greater than or equal filters for Unit"""

    smaller_or_equal: Annotated[
        OptionalNullable[UnitFilterSmallerOrEqual],
        pydantic.Field(alias="smallerOrEqual"),
    ] = UNSET
    r"""Smaller than or equal filters for Unit"""

    contains: OptionalNullable[UnitFilterContains] = UNSET
    r"""Contains filters for Unit"""

    not_contains: Annotated[
        OptionalNullable[UnitFilterNotContains], pydantic.Field(alias="notContains")
    ] = UNSET
    r"""Not contains filters for Unit"""

    like: OptionalNullable[UnitFilterLike] = UNSET
    r"""LIKE filters for Unit"""

    not_like: Annotated[
        OptionalNullable[UnitFilterNotLike], pydantic.Field(alias="notLike")
    ] = UNSET
    r"""NOT LIKE filters for Unit"""

    null: OptionalNullable[UnitFilterNull] = UNSET
    r"""Null filters for Unit"""

    not_null: Annotated[
        OptionalNullable[UnitFilterNotNull], pydantic.Field(alias="notNull")
    ] = UNSET
    r"""Not null filters for Unit"""

    nested_filters: Annotated[
        Optional[List[UnitFilter]], pydantic.Field(alias="nestedFilters")
    ] = None
    r"""NestedFilters of the Unit, useful for more complex filters"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "equals",
                "notEquals",
                "greaterThan",
                "smallerThan",
                "greaterOrEqual",
                "smallerOrEqual",
                "contains",
                "notContains",
                "like",
                "notLike",
                "null",
                "notNull",
                "nestedFilters",
            ]
        )
        nullable_fields = set(
            [
                "equals",
                "notEquals",
                "greaterThan",
                "smallerThan",
                "greaterOrEqual",
                "smallerOrEqual",
                "contains",
                "notContains",
                "like",
                "notLike",
                "null",
                "notNull",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    UnitFilterEqualsMeta.model_rebuild()
except NameError:
    pass
try:
    UnitFilterEqualsExternal.model_rebuild()
except NameError:
    pass
try:
    UnitFilterNotEqualsMeta.model_rebuild()
except NameError:
    pass
try:
    UnitFilterNotEqualsExternal.model_rebuild()
except NameError:
    pass
try:
    UnitFilterGreaterThanMeta.model_rebuild()
except NameError:
    pass
try:
    UnitFilterSmallerThanMeta.model_rebuild()
except NameError:
    pass
try:
    UnitFilterGreaterOrEqualMeta.model_rebuild()
except NameError:
    pass
try:
    UnitFilterSmallerOrEqualMeta.model_rebuild()
except NameError:
    pass
try:
    UnitFilterContainsMeta.model_rebuild()
except NameError:
    pass
try:
    UnitFilterContainsExternal.model_rebuild()
except NameError:
    pass
try:
    UnitFilterNotContainsMeta.model_rebuild()
except NameError:
    pass
try:
    UnitFilterNotContainsExternal.model_rebuild()
except NameError:
    pass
try:
    UnitFilterLikeExternal.model_rebuild()
except NameError:
    pass
try:
    UnitFilterNotLikeExternal.model_rebuild()
except NameError:
    pass
try:
    UnitFilterNullMeta.model_rebuild()
except NameError:
    pass
try:
    UnitFilterNullExternal.model_rebuild()
except NameError:
    pass
try:
    UnitFilterNotNullMeta.model_rebuild()
except NameError:
    pass
try:
    UnitFilterNotNullExternal.model_rebuild()
except NameError:
    pass
try:
    UnitFilter.model_rebuild()
except NameError:
    pass
