"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from meitner.errors import MeitnerError
from meitner.models import (
    unitcreate422responsebody_error as models_unitcreate422responsebody_error,
)
from meitner.types import BaseModel
from typing import Optional


class UnitCreate422ResponseBodyErrorData(BaseModel):
    error: models_unitcreate422responsebody_error.UnitCreate422ResponseBodyError


@dataclass(unsafe_hash=True)
class UnitCreate422ResponseBodyError(MeitnerError):
    r"""Validation error for Unit Create operation - request data failed validation"""

    data: UnitCreate422ResponseBodyErrorData = field(hash=False)

    def __init__(
        self,
        data: UnitCreate422ResponseBodyErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.error.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
